#!/bin/bash

invoker=$(src/invoker)

if [[ "$invoker" == \"\"  ]] && [[ $1 == "clear" || $# -lt 1  ]]; then
    echo "Python invoker not set! Please run ./config <python invoker>, for example ./config python3"
    echo "See TODO for more info"
else
    # insert repo_path into config
    cat dev_config.json | jq --indent 4 --sort-keys --arg dir $(pwd) '.paths.repo_path |= $dir' > tmp_config.json
    mv tmp_config.json dev_config.json

    cd src
    if [[ $1 == "clear" ]]; then
        echo Need to implement clear
    elif [[ $# -gt 0 ]]; then
        echo Need to implement invoker
    else
        $invoker config.py --noauth_local_webserver
    fi
fi
