#!/bin/bash

r1=$(pgrep -f send.py)
r2=$(pgrep -f receive.py)

# repo_path variable added here by config script
{repo_path_cmd}

cd $repo_path

invoker=$(src/invoker)

cd $repo_path/src
if [ -z $r1 ] || [ -z $r2 ]; then
    if [ -z $r1 ]; then
        $invoker -u timedate.py "send.py not running" >> ../output.txt
    fi

    if [ -z $r2 ]; then
        $invoker -u timedate.py "receive.py not running" >> ../output.txt
    fi

    $invoker -u timedate.py "Re-running send and receive" >> ../output.txt
    ../kill
    ../send/start $invoker &
    ../receive/start $invoker &
else
    $invoker -u timedate.py "Still running" >> ../output.txt
fi
